"""
***
This program was generated by copilot with the prompt:
create a python program to make a thematic analysis of interview data
***

I've created a Python program that performs thematic analysis on
interview data using Latent Dirichlet Allocation (LDA). Here's a
summary of how it works:

1. ** Preprocessing **: The text data is cleaned by removing non
    - alphabetic characters and converting everything to
    lowercase.
2. ** Vectorization **: The cleaned text data is converted into a
    matrix of token counts.
3. ** LDA **: The LDA model is applied to identify topics within
    the text data.
4. ** Output **: The program outputs the top words associated with
    each identified topic.

Here's an example of how the program works with some sample interview data:
"""
##
import re
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('TkAgg', force=True)
# import function for plotting
#from session08_NMF_LDA import plot_top_words
def plot_top_words(model, feature_names, n_top_words, title):
    fig, axes = plt.subplots(2, 3, figsize=(30, 15), sharex=True)
    axes = axes.flatten()
    for topic_idx, topic in enumerate(model.components_):
        top_features_ind = topic.argsort()[-n_top_words:]
        top_features = feature_names[top_features_ind]
        weights = topic[top_features_ind]

        ax = axes[topic_idx]
        ax.barh(top_features, weights, height=0.7)
        ax.set_title(f"Topic {topic_idx +1}", fontdict={"fontsize": 10})
        ax.tick_params(axis="both", which="major", labelsize=10)
        for i in "top right left".split():
            ax.spines[i].set_visible(False)
        fig.suptitle(title, fontsize=15)

    plt.subplots_adjust(top=0.90, bottom=0.05, wspace=0.90, hspace=0.3)
    plt.show()


## Function to clean and preprocess the text data
def preprocess_text(text):
    # Remove non-alphabetic characters and convert to lowercase
    text = re.sub(r'[^a-zA-Z\s]', '', text).lower()
    return text


# Function to perform thematic analysis using LDA
def thematic_analysis(text_data, num_topics=5, num_words=10):
    # Preprocess the text data
    cleaned_data = [preprocess_text(text) for text in text_data]

    # Vectorize the text data
    vectorizer = CountVectorizer(ngram_range=(1,2), max_df=0.8, min_df=1, stop_words='english')
    text_matrix = vectorizer.fit_transform(cleaned_data)

    # Perform LDA
    lda = LatentDirichletAllocation(n_components=num_topics, random_state=42)
    lda.fit(text_matrix)

    # Get the topics and their corresponding words
    words = vectorizer.get_feature_names_out()
    topics = []
    for topic_idx, topic in enumerate(lda.components_):
        topic_words = [words[i] for i in topic.argsort()[:-num_words - 1:-1]]
        topics.append(topic_words)
    plot_top_words(lda, words, 10, "Topics in LDA model")
    return topics


# Example interview data
interview_data = [
    "I think the new policy is very effective. It has improved our workflow significantly.",
    "The new policy is good, but it needs some adjustments to be more effective.",
    "I don't like the new policy. It has made things more complicated.",
    "The new policy is okay. It has its pros and cons.",
    "I love the new policy! It has made my work much easier."
]
# load some data in this case is the novel Frankenstein
with open('Frankenstein.txt', encoding='utf-8-sig', newline=None) as file_object:
    contents = file_object.read()
contents_ = contents.split('.')
chapters = list()
for i in range(0, len(contents_)-1):
    contents_[i] = re.sub('\n', '', contents_[i])
    if len(contents_[i]) > 20 and 'IN THREE VOL' not in contents_[i]:
        chapters.append(contents_[i])

chapters = chapters[11:-107]
# Perform thematic analysis on the interview data
topics = thematic_analysis(chapters)

# Print the identified topics and their corresponding words
for idx, topic in enumerate(topics):
    print(f"Topic {idx + 1}: {', '.join(topic)}")


# """
# **Prompt: Can you explain LDA in more detail?**
#
# Sure! Latent Dirichlet Allocation (LDA) is a powerful technique used in natural
# language processing for topic modeling. Here's a detailed explanation:
#
# ### What is LDA?
# LDA is a **generative probabilistic model** that helps discover the hidden
# thematic structure in a collection of documents. It assumes that each document
# is a mixture of a small number of topics and that each word in the document is
# attributable to one of the document's topics¹(https://www.ibm.com/topics/latent-dirichlet-allocation)
# ²(https://en.wikipedia.org/wiki/Latent_Dirichlet_allocation).
#
# ### How Does LDA Work?
# 1. **Generative Process**:
#    - **Topics**: LDA assumes there are \( K \) topics shared across the corpus.
#    Each topic is a distribution over words.
#    - **Documents**: Each document is generated by first choosing a distribution
#    over topics. Then, for each word in the document, a topic is chosen from this
#    distribution, and a word is generated from the corresponding topic's distribution.
#
# 2. **Mathematical Representation**:
#    - **Dirichlet Distribution**: LDA uses Dirichlet distributions to model the
#    distribution of topics in documents and the distribution of words in topics.
#    The Dirichlet distribution is a family of continuous multivariate probability
#    distributions parameterized by a vector of positive reals.
#    - **Plate Notation**: In plate notation, LDA is represented as a three-level
#    hierarchical Bayesian model. The outer plate represents documents, the inner
#    plate represents the repeated choice of topics and words within a
#    document²(https://en.wikipedia.org/wiki/Latent_Dirichlet_allocation).
#
# 3. **Inference**:
#    - The goal of LDA is to reverse the generative process to infer the hidden
#    topic structure. This involves estimating the distribution of topics in each
#    document and the distribution of words in each topic.
#    - **Gibbs Sampling**: One common method for performing this inference is Gibbs
#    sampling, a Markov Chain Monte Carlo (MCMC) algorithm. It iteratively samples
#    from the conditional distributions of each variable given the current values
#    of the other variables¹(https://www.ibm.com/topics/latent-dirichlet-allocation).
#
# ### Applications of LDA
# - **Topic Discovery**: Identifying the main themes in a large collection of documents.
# - **Document Classification**: Classifying documents based on their topic distributions.
# - **Information Retrieval**: Improving search engines by indexing documents based on
# their topics.
# - **Recommendation Systems**: Recommending content based on the topics of previously
# consumed content.
#
# ### Example
# Imagine you have a collection of news articles. LDA can help you identify topics like
# "politics," "sports," "technology," etc., and determine the proportion of each topic
# in every article. This way, you can understand the main themes and categorize the
# articles accordingly.
#
# If you have any specific questions or need further clarification, feel free to ask!
#
# [IBM](https://www.ibm.com/topics/latent-dirichlet-allocation)
# [Wikipedia](https://en.wikipedia.org/wiki/Latent_Dirichlet_allocation)
#
# Source: Conversation with Copilot, 11/8/2024
# (1) What is Latent Dirichlet allocation | IBM. https://www.ibm.com/topics/latent-dirichlet-allocation.
# (2) Latent Dirichlet allocation - Wikipedia. https://en.wikipedia.org/wiki/Latent_Dirichlet_allocation.
#
# """